friends = ['mani','suna','newton','sadikul','kamal'] # this is a list and it can ad any thing like strings,bool,intiger etc and it is created by []
print(friends)
friends.reverse()
print(friends)
friends.sort()
print(friends)
friends.append('julfikar')
print(friends)
friends.insert(3,'chand')
print(friends)
friends.pop(3)
print(friends)
friends.remove('julfikar')
print(friends)