a=int(input('Enter the first number: '))
b=int(input('Enter the second number: '))
c=int(input('Enter the third number: '))
d=int(input('Enter the fourth number: '))
e=int(input('Enter the fifth number: '))
f=int(input('Enter the sixth number: '))
g=int(input('Enter the seventh number: '))
h=int(input('Enter the eighth number: '))
s ={a,b,c,d,e,f,g,h}
print(s)
